dist: trusty
sudo: false
language: scala
cache:
  directories:
    - $HOME/.ivy2
env:
  - NODE_VERSION=11
scala:
  - 2.12.6
jdk:
  - oraclejdk8
script:
  - nvm use $NODE_VERSION
  - cd app-ui && npm install && npm run-script build && cd ..
  - sbt stage -DtsCompileMode=stage
